# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

##
# PostgreSQL
#   gem install pg
#
# development:
#   adapter:  postgresql
#   database: pilfer_server_development
#   username: ???
#
# test:
#   adapter:  postgresql
#   database: pilfer_server_test
#   username: ???

##
# MySQL
#   gem install ???
#
# development:
#   adapter:  ???
#   database: pilfer_server_development
#   username: ???
#
# test:
#   adapter:  ???
#   database: pilfer_server_test
#   username: ???
